import type { Category } from "./protocol";
export interface Question { category: Category; title: string; artifactLabel: string; artifact: string; prompt: string; options: string[]; correct: number; explanation: string; concept: string }
// This bank is imported only by the server. Correct answers never enter the client bundle.
export const questions: Question[] = [
  {category:"Spot the trap",title:"The payroll panic",artifactLabel:"INBOX · NEW MESSAGE",artifact:"From: Payroll <payroll@company-pay.example>\nSubject: Your paycheck is on hold!\n\nSign in through this link within 10 minutes or your salary will be delayed.",prompt:"What's your safest move?",options:["Open payroll through your usual saved site","Use the email link before the timer runs out","Reply with your password to verify your identity"],correct:0,explanation:"Urgency and an unfamiliar sender are phishing clues. Visit the service through a known route and check with payroll separately.",concept:"Phishing"},
  {category:"Spot the trap",title:"The mystery USB",artifactLabel:"FOUND · BREAK ROOM",artifact:"A USB drive labeled “Salary list — confidential” is lying beside the coffee machine. No one knows who left it.",prompt:"What do you do with it?",options:["Give it to your IT or security team","Plug it in to see who owns it","Try it on someone else's laptop"],correct:0,explanation:"An unknown USB drive can install malware when connected. Let the security team handle it without plugging it in.",concept:"Social engineering"},
  {category:"Spot the trap",title:"The boss has a favor",artifactLabel:"TEAM CHAT · DIRECT MESSAGE",artifact:"“I'm in a meeting. Buy $300 in gift cards and send me the codes. Don't call me — it's urgent.”\n\nThe profile photo looks like your manager.",prompt:"What happens next?",options:["Call your manager using a number you already know","Buy the cards and ask for reimbursement","Send half the codes as a compromise"],correct:0,explanation:"A familiar photo is easy to copy. Verify unusual money requests through another trusted channel.",concept:"Impersonation"},
  {category:"Spot the trap",title:"An update you expected",artifactLabel:"DEVICE SETTINGS · SOFTWARE UPDATE",artifact:"You opened your laptop's built-in Settings app. It offers a signed security update from the operating system vendor.",prompt:"Which response is best?",options:["Install it through the Settings app","Ignore all updates in case they're malware","Search for an unofficial download mirror"],correct:0,explanation:"Updates from the built-in updater fix known weaknesses. Use the official route rather than unsolicited links or unofficial downloads.",concept:"Security patches"},
  {category:"Spot the trap",title:"Support wants your code",artifactLabel:"PHONE CALL · INCOMING",artifact:"A caller says they're from your bank. They ask you to read out the one-time login code that just arrived on your phone.",prompt:"How should you respond?",options:["Hang up and contact the bank through its official number","Read the code because it expires soon","Ask for their name, then share the code"],correct:0,explanation:"A one-time login code can let someone into your account. Don't share it with a caller, even one claiming to be support.",concept:"MFA code theft"},
  {category:"Spot the trap",title:"The QR shortcut",artifactLabel:"POSTER · PARKING GARAGE",artifact:"A sticker covers the parking meter's original QR code: “Payment system upgraded. Scan here.” The new page asks for your card details.",prompt:"What's the safest way to pay?",options:["Use the official parking app or meter controls","Trust the sticker because it looks professional","Enter your card details and check later"],correct:0,explanation:"Attackers can replace QR codes with links to fake payment sites. Use a known payment route instead.",concept:"QR phishing"},
  {category:"Stop the breach",title:"Your files are locked",artifactLabel:"SECURITY ALERT · LAPTOP",artifact:"Your files suddenly have strange extensions. A message demands cryptocurrency to unlock them. Your laptop is still on the office network.",prompt:"What's the best first action?",options:["Disconnect it from the network and contact IT","Keep working and hope the message disappears","Plug in the backup drive immediately"],correct:0,explanation:"Disconnecting helps contain ransomware. Contact IT before attaching backups or trying recovery.",concept:"Ransomware containment"},
  {category:"Stop the breach",title:"You clicked. Now what?",artifactLabel:"INCIDENT · ACCOUNT",artifact:"You entered your work password on a suspicious site. A moment later, you notice the web address was wrong.",prompt:"What's your best response?",options:["Report it and change the password on the real service","Wait to see whether anyone uses the account","Delete the browser history and forget about it"],correct:0,explanation:"Fast reporting lets the team revoke stolen sessions. Change the exposed password through the real service and secure any accounts that reused it.",concept:"Credential compromise"},
  {category:"Stop the breach",title:"The accidental share",artifactLabel:"CLOUD DRIVE · SHARING ALERT",artifact:"A spreadsheet with customer information is set to “Anyone with the link.” It should only be available to your project team.",prompt:"How do you respond?",options:["Restrict access and report the exposure","Rename the file to make it harder to find","Leave it open so work isn't interrupted"],correct:0,explanation:"Restrict access promptly and report the exposure so the organization can investigate who accessed it.",concept:"Data exposure"},
  {category:"Stop the breach",title:"The login you didn't make",artifactLabel:"ACCOUNT ALERT · NEW SIGN-IN",artifact:"Your account reports a successful sign-in from an unfamiliar device. You didn't sign in, and your phone hasn't left your pocket.",prompt:"What should you do?",options:["Open the official service, revoke unknown sessions, and reset the password","Dismiss it because your phone is safe","Reply to the alert with your password"],correct:0,explanation:"A stolen password or session can work without physical access to your phone. Revoke unknown sessions and secure the account through the official service.",concept:"Account takeover"},
  {category:"Stop the breach",title:"A hundred approval prompts",artifactLabel:"PHONE · LOGIN REQUESTS",artifact:"Your authenticator keeps asking you to approve sign-ins you didn't start. The prompts are getting annoying.",prompt:"How do you stop the problem safely?",options:["Deny the prompts and report them","Approve one to make the notifications stop","Turn off account security notifications"],correct:0,explanation:"Repeated prompts can be an MFA fatigue attack. Deny unexpected requests and report them; never approve one just to stop the noise.",concept:"MFA fatigue"},
  {category:"Stop the breach",title:"Lost on the train",artifactLabel:"INCIDENT · MISSING DEVICE",artifact:"You left a work laptop on the train. It contains company data. You have a phone and can still contact your workplace.",prompt:"What is your first move?",options:["Tell IT so they can lock it and revoke access","Wait a few days in case it turns up","Post the laptop password in a lost-and-found group"],correct:0,explanation:"Quick reporting lets IT lock or wipe managed devices and revoke access. Device encryption adds protection, but doesn't replace reporting.",concept:"Device security"},
  {category:"Build the shield",title:"One password, ten accounts",artifactLabel:"SECURITY CHECK · ACCOUNT SETUP",artifact:"Your favorite password is already used for email, shopping, and gaming. You're creating a new account today.",prompt:"Choose the strongest habit.",options:["Generate a unique password with a password manager","Reuse it, but add an exclamation point","Share it with a friend so someone remembers it"],correct:0,explanation:"Unique passwords stop one breach from unlocking many accounts. A password manager helps create and store them.",concept:"Password reuse"},
  {category:"Build the shield",title:"Guests on the network",artifactLabel:"NETWORK PLAN · SMALL OFFICE",artifact:"Visitors need Wi-Fi. Staff laptops and the payroll server use the office network too.",prompt:"Which setup gives the office better protection?",options:["A separate guest network with no access to internal systems","One shared Wi-Fi password for everyone","Turn off the firewall to simplify connections"],correct:0,explanation:"Network segmentation separates visitors from sensitive systems and limits where an attacker can move.",concept:"Network segmentation"},
  {category:"Build the shield",title:"The backup dilemma",artifactLabel:"RECOVERY PLAN · FILES",artifact:"All your files and the only backup are on the same laptop. You're planning for theft or ransomware.",prompt:"Which plan is stronger?",options:["Keep separate backups, including an offline or protected copy","Make another folder on the same laptop","Email every file to a stranger for safekeeping"],correct:0,explanation:"A backup on the same device can disappear with it. Separate, protected copies and tested restores make recovery possible.",concept:"Resilient backups"},
  {category:"Build the shield",title:"The intern's permissions",artifactLabel:"ACCESS REQUEST · NEW TEAMMATE",artifact:"A new intern needs to view one project folder. The admin panel can also grant full access to every company file.",prompt:"What access should you grant?",options:["Only the project folder and permissions needed for the job","Admin access so they never need to ask again","Your own account so setup is faster"],correct:0,explanation:"Least privilege means granting only the access needed. It reduces the damage from mistakes or compromised accounts.",concept:"Least privilege"},
  {category:"Build the shield",title:"A password isn't enough",artifactLabel:"ACCOUNT SETTINGS · SECURITY",artifact:"Your email account protects resets for all your other accounts. You can add a second sign-in factor.",prompt:"Which setting offers the best protection here?",options:["Enable a passkey or security key where supported","Use the same password with a different username","Put the password in your public profile"],correct:0,explanation:"Passkeys and security keys resist many phishing attacks. Stronger sign-in protection is especially valuable for your main email account.",concept:"Phishing-resistant authentication"},
  {category:"Build the shield",title:"The café connection",artifactLabel:"WI-FI · PUBLIC HOTSPOT",artifact:"You're on café Wi-Fi. A browser warning says the connection to your bank is not secure and the certificate is invalid.",prompt:"Choose the safe next step.",options:["Stop, then use a trusted connection and the official bank app","Bypass the warning because the café has good reviews","Enter the password quickly before anyone notices"],correct:0,explanation:"Don't bypass certificate warnings for sensitive activity. A trusted connection and official app are safer routes.",concept:"Secure connections"},
];
